
using Microsoft.Maui.Handlers;

namespace Plugin.Maui.Barkoder.Controls
{
    public partial class BarkoderViewHandler
    {

        public BarkoderViewHandler() : base(PropertyMapper, CommandMapper) { }

        public static IPropertyMapper<BarkoderView, BarkoderViewHandler> PropertyMapper =
            new PropertyMapper<BarkoderView, BarkoderViewHandler>(ViewHandler.ViewMapper)
            {
                [nameof(BarkoderView.LicenseKey)] = MapLicenseKey,
                [nameof(BarkoderView.RegionOfInterestVisible)] = MapRegionOfInterestVisible,
                [nameof(BarkoderView.IsFlashAvailableProperty)] = MapIsFlashAvailable,
                [nameof(BarkoderView.ARImageResultEnabled)] = MapARImageResultEnabled,
                [nameof(BarkoderView.ARBarcodeThumbnailOnResultEnabled)] = MapARBarcodeThumbnailOnResultEnabled,
                //[nameof(BarkoderView.MaxZoomFactorProperty)] = MapMaxZoomFactor,
                [nameof(BarkoderView.LocationLineColorHexProperty)] = MapLocationLineColorHex,
                [nameof(BarkoderView.ARNonSelectedLocationLineColorHexProperty)] = MapARNonSelectedLocationLineColorHex,
                [nameof(BarkoderView.ARSelectedLocationLineColorHexProperty)] = MapARSelectedLocationLineColorHex,
                [nameof(BarkoderView.ARSelectedHeaderTextColorHexProperty)] = MapARSelectedHeaderTextColorHex,
                [nameof(BarkoderView.ARNonSelectedHeaderTextColorHexProperty)] = MapARNonSelectedHeaderTextColorHex,
                [nameof(BarkoderView.RoiLineColorHexProperty)] = MapRoiLineColorHex,
                [nameof(BarkoderView.RoiOverlayBackgroundColorHexProperty)] = MapRoiOverlayBackgroundColorHex,
                [nameof(BarkoderView.EncodingCharacterSetProperty)] = MapEncodingCharacterSet,
                [nameof(BarkoderView.ARHeaderTextFormatProperty)] = MapARHeaderTextFormat,
                [nameof(BarkoderView.LocationLineWidthProperty)] = MapLocationLineWidth,
                [nameof(BarkoderView.ARSelectedLocationLineWidthProperty)] = MapARSelectedLocationLineWidth,
                [nameof(BarkoderView.ARNonSelectedLocationLineWidthProperty)] = MapARNonSelectedLocationLineWidth,
                [nameof(BarkoderView.ARLocationTransitionSpeedProperty)] = MapARLocationTransitionSpeed,
                [nameof(BarkoderView.ImageResultEnabledProperty)] = MapImageResultEnabled,
                [nameof(BarkoderView.LocationInImageResultEnabledProperty)] = MapLocationInImageResultEnabled,
                [nameof(BarkoderView.LocationInPreviewEnabledProperty)] = MapLocationInPreviewEnabled,
                [nameof(BarkoderView.PinchToZoomEnabledProperty)] = MapPinchToZoomEnabled,
                [nameof(BarkoderView.BeepOnSuccessEnabledProperty)] = MapBeepOnSuccessEnabled,
                [nameof(BarkoderView.VibrateOnSuccessEnabledProperty)] = MapVibrateOnSuccessEnabled,
                [nameof(BarkoderView.CloseSessionOnResultEnabledProperty)] = MapCloseSessionOnResultEnabled,
                [nameof(BarkoderView.ARContinueScanningOnLimitProperty)] = MapARContinueScanningOnLimit,
                [nameof(BarkoderView.AREmitResultsAtSessionEndOnlyProperty)] = MapAREmitResultsAtSessionEndOnly,
                [nameof(BarkoderView.ARResultLimitProperty)] = MapARResultLimit,
                [nameof(BarkoderView.VersionProperty)] = MapVersion,
                [nameof(BarkoderView.LibVersionProperty)] = MapLibVersion,
                [nameof(BarkoderView.BarkoderResolutionProperty)] = MapBarkoderResolution,
                [nameof(BarkoderView.BarkoderARModeProperty)] = MapBarkoderARMode,
                [nameof(BarkoderView.BarkoderARHeaderShowModeProperty)] = MapBarkoderARHeaderShowMode,
                [nameof(BarkoderView.BarkoderARLocationTypeProperty)] = MapBarkoderARLocationType,
                [nameof(BarkoderView.DecodingSpeedProperty)] = MapDecodingSpeed,
                [nameof(BarkoderView.FormattingTypeProperty)] = MapFormattingType,
                [nameof(BarkoderView.MsiChecksumTypeProperty)] = MapMsiChecksumType,
                [nameof(BarkoderView.Code11ChecksumTypeProperty)] = MapCode11ChecksumType,
                [nameof(BarkoderView.Code39ChecksumTypeProperty)] = MapCode39ChecksumType,
                [nameof(BarkoderView.DatamatrixDpmModeEnabledProperty)] = MapDatamatrixDpmModeEnabled,
                [nameof(BarkoderView.ScanningIndicatorAlwaysVisibleProperty)] = MapScanningIndicatorAlwaysVisibleEnabled,
                [nameof(BarkoderView.ScanningIndicatorAnimationModeProperty)] = MapScanningIndicatorAnimationMode,
                [nameof(BarkoderView.ScanningIndicatorColorHexProperty)] = MapScanningIndicatorColor,
                [nameof(BarkoderView.ScanningIndicatorLineWidthProperty)] = MapScanningIndicatorWidth,
                [nameof(BarkoderView.DatamatrixDpmModeEnabledProperty)] = MapDatamatrixDpmModeEnabled,
                [nameof(BarkoderView.IdDocumentMasterChecksumEnabledProperty)] = MapIdDocumentMasterChecksumEnabled,
                [nameof(BarkoderView.QRDpmModeEnabledProperty)] = MapQRDpmModeEnabled,
                [nameof(BarkoderView.QRMicroDpmModeEnabledProperty)] = MapQRMicroDpmModeEnabled,
                [nameof(BarkoderView.UpcEanDeblurEnabledProperty)] = MapUpcEanDeblurEnabled,
                [nameof(BarkoderView.EnableMisshaped1DEnabledProperty)] = MapEnableMisshaped1DEnabled,
                [nameof(BarkoderView.BarcodeThumbnailOnResultEnabledProperty)] = MapBarcodeThumbnailOnResultEnabledProperty,
                [nameof(BarkoderView.MaximumResultsCountProperty)] = MapMaximumResultsCount,
                [nameof(BarkoderView.ResultDisappearanceDelayMsProperty)] = MapResultDisappearanceDelayMs,
                [nameof(BarkoderView.HeaderARVerticalTextMarginProperty)] = MapARHeaderVerticalTextMargin,
                [nameof(BarkoderView.HeaderARHorizontalTextMarginProperty)] = MapARHeaderHorizontalTextMargin,
                [nameof(BarkoderView.ARHeaderHeightProperty)] = MapARHeaderHeight,
                [nameof(BarkoderView.ARHeaderMaxTextHeightProperty)] = MapARHeaderMaxTextHeight,
                [nameof(BarkoderView.ARHeaderMinTextHeightProperty)] = MapARHeaderMinTextHeight,
                [nameof(BarkoderView.DuplicatesDelayMsProperty)] = MapDuplicatesDelayMs,
                [nameof(BarkoderView.VINRestrictionsEnabledProperty)] = MapVINRestrictionsEnabled,
                [nameof(BarkoderView.ARDoubleTapToFreezeEnabledProperty)] = MapARDoubleTapToFreezeEnabled,
                [nameof(BarkoderView.ThresholdBetweenDuplicatesScansProperty)] = MapThresholdBetweenDuplicatesScans,
                [nameof(BarkoderView.EnableCompositeProperty)] = MapEnableComposite,
                [nameof(BarkoderView.RegionOfInterestProperty)] = MapRegionOfInterest,

            };

        public static CommandMapper<BarkoderView, BarkoderViewHandler> CommandMapper = new(ViewCommandMapper)
        {

            [nameof(BarkoderView.SetCustomOption)] = MapSetCustomOption,
            [nameof(BarkoderView.SetDynamicExposure)] = MapSetDynamicExposure,
            [nameof(BarkoderView.SetARImageResultEnabledRequested)] = MapSetARImageResultEnabled,
            [nameof(BarkoderView.SetARBarcodeThumbnailOnResultEnabledRequested)] = MapSetARBarcodeThumbnailOnResultEnabled,
            [nameof(BarkoderView.SetCamera)] = MapSetCamera,
            [nameof(BarkoderView.SetCentricFocusAndExposure)] = MapSetCentricFocusAndExposure,
            [nameof(BarkoderView.SetUPCE1expandToUPCA)] = MapSetUPCE1expandToUPCA,
            [nameof(BarkoderView.SetShowDuplicatesLocation)] = MapSetShowDuplicatesLocation,
            [nameof(BarkoderView.SetUPCEexpandToUPCA)] = MapSetUPCEexpandToUPCA,
            [nameof(BarkoderView.SetVideoStabilization)] = MapSetVideoStabilization,
            [nameof(BarkoderView.StartCameraRequested)] = MapStartCamera,
            [nameof(BarkoderView.StartScanningRequested)] = MapStartScanning,
            [nameof(BarkoderView.ScanImageRequest)] = MapScanImage,
            [nameof(BarkoderView.StopScanningRequested)] = MapStopScanning,
            [nameof(BarkoderView.SelectVisibleBarcodesRequested)] = MapSelectVisibleBarcodes,
            [nameof(BarkoderView.ConfigureCloseButtonRequested)] = MapConfigureCloseButton,
            [nameof(BarkoderView.ConfigureFlashButtonRequested)] = MapConfigureFlashButton,
            [nameof(BarkoderView.ConfigureZoomButtonRequested)] = MapConfigureZoomButton,
            [nameof(BarkoderView.CaptureImageRequested)] = MapCaptureImage,
            [nameof(BarkoderView.PauseScanningRequested)] = MapPauseScanning,
            [nameof(BarkoderView.FreezeScanningRequested)] = MapFreezeScanning,
            [nameof(BarkoderView.UnfreezeScanningRequested)] = MapUnfreezeScanning,
            [nameof(BarkoderView.FlashEnableRequested)] = MapFlashEnable,
            [nameof(BarkoderView.SetZoomFactorRequested)] = MapSetZoomFactor,
            [nameof(BarkoderView.SetPinchToZoomEnabledRequested)] = MapSetPinchToZoomEnabled,
            [nameof(BarkoderView.SetRegionOfInterestVisibleRequested)] = MapSetRegionOfInterestVisible,
            [nameof(BarkoderView.SetRoiLineWidthRequested)] = MapSetRoiLineWidth,
            [nameof(BarkoderView.SetCloseSessionOnResultEnabledRequested)] = MapSetCloseSessionOnResult,
            [nameof(BarkoderView.SetARContinueScanningOnLimitRequested)] = MapSetARContinueScanningOnLimit,
            [nameof(BarkoderView.SetAREmitResultsAtSessionEndOnlyRequested)] = MapSetAREmitResultsAtSessionEndOnly,
            [nameof(BarkoderView.SetImageResultEnabledRequested)] = MapSetImageResultEnabled,
            [nameof(BarkoderView.SetLocationInPreviewEnabledRequested)] = MapSetLocationInPreviewEnabled,
            [nameof(BarkoderView.SetLocationInImageResultEnabledRequested)] = MapSetLocationInImageResultEnabled,
            [nameof(BarkoderView.SetBeepOnSuccessEnabledRequested)] = MapSetBeepOnSuccessEnabled,
            [nameof(BarkoderView.SetVibrateOnSuccessEnabledRequested)] = MapSetVibrateOnSuccessEnabled,
            [nameof(BarkoderView.SetLocationLineColorRequested)] = MapSetLocationLineColor,
            [nameof(BarkoderView.InitCameraProperties)] = MapInitCameraProperties,
            [nameof(BarkoderView.SetARNonSelectedLocationLineColorRequested)] = MapSetARNonSelectedLocationColor,
            [nameof(BarkoderView.SetARSelectedLocationLineColorRequested)] = MapSetARSelectedLocationColor,
            [nameof(BarkoderView.SetARSelectedHeaderTextColorRequested)] = MapSetARSelectedHeaderTextColor,
            [nameof(BarkoderView.SetARNonSelectedHeaderTextColorRequested)] = MapSetARNonSelectedHeaderTextColor,
            [nameof(BarkoderView.SetRoiLineColorRequested)] = MapSetRoiLineColor,
            [nameof(BarkoderView.SetRoiOverlayBackgroundColorRequested)] = MapSetRoiOverlayBackgroundColor,
            [nameof(BarkoderView.SetLocationLineWidthRequested)] = MapSetLocationLineWidth,
            [nameof(BarkoderView.SetARNonSelectedLocationLineWidthRequested)] = MapSetARNonSelectedLocationLineWidth,
            [nameof(BarkoderView.SetARLocationTransitionSpeedRequested)] = MapSetARLocationTransitionSpeed,
            [nameof(BarkoderView.SetARSelectedLocationLineWidthRequested)] = MapSetARSelectedLocationLineWidth,
            [nameof(BarkoderView.SetRegionOfInterestRequested)] = MapSetRegionOfInterest,
            [nameof(BarkoderView.SetBarkoderResolutionRequested)] = MapSetBarkoderResolution,
            [nameof(BarkoderView.SetBarkoderARModeRequested)] = MapSetBarkoderARMode,
            [nameof(BarkoderView.SetBarkoderARHeaderShowModeRequested)] = MapSetBarkoderARHeaderShowMode,
            [nameof(BarkoderView.SetBarkoderARLocationTypeRequested)] = MapSetBarkoderARLocationType,
            [nameof(BarkoderView.SetBarkoderARoverlayRefreshRequested)] = MapSetBarkoderARoverlayRefresh,
            [nameof(BarkoderView.SetDecodingSpeedRequested)] = MapSetDecodingSpeed,
            [nameof(BarkoderView.SetFormattingTypeRequested)] = MapSetFormattingType,
            [nameof(BarkoderView.SetMsiChecksumTypeRequested)] = MapSetMsiChecksumType,
            [nameof(BarkoderView.SetCode11ChecksumTypeRequested)] = MapSetCode11ChecksumType,
            [nameof(BarkoderView.SetCode39ChecksumTypeRequested)] = MapSetCode39ChecksumType,
            [nameof(BarkoderView.SetEncodingCharacterSetRequested)] = MapSetEncodingCharacterSet,
            [nameof(BarkoderView.SetARHeaderTextFormatRequested)] = MapSetARHeaderTextFormat,
            [nameof(BarkoderView.SetDatamatrixDpmModeEnabledRequested)] = MapSetDatamatrixDpmModeEnabled,
            [nameof(BarkoderView.SetIdDocumentMasterChecksumEnabledRequested)] = MapSetIdDocumentMasterChecksumEnabled,
            [nameof(BarkoderView.SetQRDpmModeEnabledRequested)] = MapSetQRDpmModeEnabled,
            [nameof(BarkoderView.SetQRMicroDpmModeEnabledRequested)] = MapSetQRMicroDpmModeEnabled,
            [nameof(BarkoderView.SetScanningIndicatorAlwaysVisibleRequested)] = MapSetScanningIndicatorAlwaysVisibleEnabled,
            [nameof(BarkoderView.SetScanningIndicatorLineWidthRequested)] = MapSetScanningIndicatorWidth,
            [nameof(BarkoderView.SetScanningIndicatorColorHexRequested)] = MapSetScanningIndicatorColor,
            [nameof(BarkoderView.SetScanningIndicatorAnimationModeRequested)] = MapSetScanningIndicatorAnimationMode,
            [nameof(BarkoderView.SetUpcEanDeblurEnabledRequested)] = MapSetUpcEanDeblurEnabled,
            [nameof(BarkoderView.SetEnableMisshaped1DEnabledRequested)] = MapSetEnableMisshaped1DEnabled,
            [nameof(BarkoderView.SetBarcodeThumbnailOnResultEnabledRequested)] = MapSetBarcodeThumbnailOnResultEnabled,
            [nameof(BarkoderView.SetMaximumResultsCountRequested)] = MapSetMaximumResultsCount,
            [nameof(BarkoderView.SetARResultLimitRequested)] = MapSetARResultLimit,
            [nameof(BarkoderView.SetResultDisappearanceDelayMsRequested)] = MapSetResultDisappearanceDelayMs,
            [nameof(BarkoderView.SetARHeaderVerticalTextMarginRequested)] = MapSetARHeaderVerticalTextMargin,
            [nameof(BarkoderView.SetARHeaderHorizontalTextMarginRequested)] = MapSetARHeaderHorizontalTextMargin,
            [nameof(BarkoderView.SetARHeaderHeightRequested)] = MapSetARHeaderHeight,
            [nameof(BarkoderView.SetARHeaderMaxTextHeightRequested)] = MapSetARHeaderMaxTextHeight,
            [nameof(BarkoderView.SetARHeaderMinTextHeightRequested)] = MapSetARHeaderMinTextHeight,
            [nameof(BarkoderView.SetDuplicatesDelayMsRequested)] = MapSetDuplicatesDelayMs,
            [nameof(BarkoderView.SetBarcodeTypeEnabledRequested)] = MapSetBarcodeTypeEnabled,
            [nameof(BarkoderView.SetEnableVINRestrictionsRequested)] = MapSetEnableVINRestrictions,
            [nameof(BarkoderView.SetARDoubleTapToFreezeEnabledRequested)] = MapSetDoubleTapToFreezeEnabled,
            [nameof(BarkoderView.SetThresholdBetweenDuplicatesScansRequested)] = MapSetThresholdBetweenDuplicatesScans,
            [nameof(BarkoderView.SetEnableCompositeRequested)] = MapSetEnableComposite,
            [nameof(BarkoderView.SetBarcodeTypeLengthRangeRequested)] = MapSetBarcodeTypeLengthRange,
            [nameof(BarkoderView.ConfigureBarkoderRequested)] = MapConfigureBarkoder,
        };
    }
}
